### ISSUE TITLE
General project structure

### ISSUE THREAD

**Issue by jandrej** [JuLuSi/EEBO#1]
I already pushed a first branch as an idea for the general project structure. This includes a working CMakeLists.txt and an idea how to organize our different drivers. For example my part would be in

```
src/drivers/fbc
```

the MPC and MOR/POD stuff goes into

```
src/drivers/mpc
src/drivers/mor
```

respectively.

You can basically then just add your driver to the CMakeLists by adding

```
add_executable(mor_driver
        src/driver/mor/mor.cc)
target_link_libraries(mor_driver eeboCommon ${LIBS})
```

Ideas?

**Comment by mechiluca** [comment]
Ok, it sounds good!

**Comment by Telos4** [comment]
Ok great, the general structure looks reasonable to me.

I checked out the branch and it works fine, after one small change:
In the CMakeLists.txt I had to specify the path to my libmesh installation (which it needs to find the pkg-config file like you explained to me yesterday). 
I would suggest that we read that path from an environment variable instead (e.g. $LIBMESH_DIR).
Then we just have to set the local environment variable accordingly and won't have to modify the CMakeLists.txt file anymore.

**Comment by mechiluca** [comment]
I agree

**Comment by jandrej** [comment]
>  would suggest that we read that path from an environment variable instead (e.g. $LIBMESH_DIR).
> Then we just have to set the local environment variable accordingly and won't have to modify the CMakeLists.txt file anymore.

Yep, this can also be done with

```
cmake -DLIBMESH_DIR=$HOME/libmesh
```

**Comment by jandrej** [comment]
I added the LIBMESH_DIR change and also provide a Travis config which builds from scratch in ~25minutes and with cache in ~45sec. The non-cache installs system dependencies and compiles petsc and libmesh. So basically we have an installation script here!

I will merge the changes into the the master branch in a minute.
