### ISSUE TITLE
Dynamically search for lib or lib64 path

### ISSUE THREAD

**Issue by jandrej** [JuLuSi/EEBO#2]
On OpenSuse libmesh decides to install the pkgconfig files into 

```
${LIBMESH_DIR}/lib64/pkgconfig
```

instead of

```
${LIBMESH_DIR}/lib/pkgconfig
```

which is ok, but we need to check for that in order to get that working. @mechiluca can you check if you can manage to edit the CMakeLists.txt so it checks for that? The corresponding code is

```
# libMesh
if (LIBMESH_DIR)
    set(ENV{PKG_CONFIG_PATH} ${LIBMESH_DIR}/lib/pkgconfig)
endif ()
```

I really don't know if there is a convention to check for lib/lib32/lib64 so it works on every system.

**Comment by mechiluca** [comment]
I modified the CMakeLists.txt on my computer, I did cmake .. and make and it works if I put /lib instead of /lib64, so it isn't a problem

**Comment by jandrej** [comment]
But if you commit you changes that gets overwritten for everyone else and then it doesn't work for me/simon.

**Comment by mechiluca** [comment]
even if I use 

# libMesh

if (LIBMESH_DIR)
    set(ENV{PKG_CONFIG_PATH} ${LIBMESH_DIR}/lib/pkgconfig)
endif ()
in my file too?
(it works with that on my computer)

**Comment by jandrej** [comment]
oh ok i  thought you need to modify the CMakeLists.txt so it finds the path on your OpenSuse system.

**Comment by mechiluca** [comment]
it works with both XD after the delete of the previous file yesterday it works with everything we tried before (I don't know why but it's fine :smile: )
